### ISSUE TITLE
Add configuration for cookie session / expiration

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#537] opened 2017-05-12 19:43 UTC
The OpenID Connect browser session is controlled via `expires/max-age` cookie value. Right now it is set to "Session" value. It means that cookie does not have expiration until user closes/kill current browser. 

There should be a JSON property that enables the admin to control this value. If cookie value, either setting it to "Session" or setting a length of time for the cookie to stay active.

**Comment by yuriyz** [comment] 2017-06-01 07:16
@worm333 I believe we need "sessionStateLifetime" property which controls sessionState life time, both cookie and in storage (cache/ldap). Right now it seems to set expiration for cookie only.

**Comment by yuriyz** [comment] 2017-06-01 07:34
Close as duplicate of #333. Futher work is going to be done withing #333

**Closed by yuriyz** 2017-06-01 07:34 UTC
Labels: enhancement
