### ISSUE TITLE
Add method to Person Authn Script to send context to proposed Post-Authn Interception Script

### ISSUE THREAD

**Issue by aliaksander-samuseu** [GluuFederation/oxAuth#1174] opened 2019-10-11 19:19 UTC
This proposal is related to another one [here](https://github.com/GluuFederation/oxAuth/issues/1129) and originates from the same customer's ticket (7337).

I'll quote Michael's suggestion from above first:
>After the browser has a session, if a person visits a website, the RP can obtain a code without the user having to authenticate or authorize. In some cases, it is desirable to insert custom business logic before granting the code or tokens from the authorization endpoint. 

Michael's suggestion adds a globally scoped custom script type allowing to re-validate ongoing session when authz request is received. By "globally scoped" here I mean acting similar to how Application Session scripts acts (i.e. inserts custom logic at start or end of **any** session). But as the customer noted in subsequent discussion, such global script may have difficulties accessing context of specific authentication script that created current session.

It may be useful to have a new method in the person authentication script itself, similar to the "logout()" method which would only be available for scripts supporting the most recent version of API (declarated with `getApiVersion()` function) and would be called by oxAuth for all sessions created using corresponding auth method when a new OIDC authz request arrives - to decide whether SSO should be used for it, or (for example) re-authentication must be forced instead.

**Comment by nynymike** [comment] 2019-10-11 20:15
I think it's a little confusing to put this in the authn script. After a user has authenticated, how do you know which script to run, if there are many authn scripts? For the current `acr`? But `acr` can be multi-value? It might be better to just add a new script for this.

**Comment by davidgvh** [comment] 2019-10-11 20:52
The current ACR would be the one to execute. If a MFA script executes, it would execute execute as it does now. The only scripts that would have an alternate execution are the federation ones, such as passport_saml and the passport_cas one that I wrote.

This can only work as a hook, since any new script would not understand the federated providers for another script unless you duplicate the configuration code from every single custom script into it. This would drastically increase the complexity. That would also mean that any new federation method would need to be implemented in two files instead of one, violating separation of concerns.

**Comment by nynymike** [comment] 2020-05-01 15:06
Non-backwards compatible because it would change the interface and require all scripts to be upgraded.

**Comment by nynymike** [comment] 2020-05-01 15:07
Closing... would be solved by **https://github.com/GluuFederation/oxAuth/issues/1129**

**Comment by yuriyz** [comment] 2020-05-13 15:47
Closed as duplicate of https://github.com/GluuFederation/oxAuth/issues/1129

**Closed by yuriyz** 2020-05-13 15:47 UTC
Labels: enhancement, non-backwards-compatitble
