### ISSUE TITLE
`refresh_ token` is automatically added to registered client in CE using oxd

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/oxAuth#1166] opened 2019-10-01 06:13 UTC
Steps:
-------
1. Register new client in using oxd `/register-site` command with `grant_types=authorization_code`.

```
curl -X POST -k -H 'Content-Type: application/json' -i https://localhost:8443/register-site --data '{
  "redirect_uris": [
    "https://localhost:5053/authorization",
    "https://localhost:5053/authorization/page1",
    "https://localhost:5053/authorization/page2"
  ],
  "op_host": "https://ce-dev6.gluu.org",
  "client_name": "register_site_2",
  "grant_types": ["authorization_code"]
}'
```

2. `refresh_ token` is automatically added to client registered in CE
![ce1](https://user-images.githubusercontent.com/32794267/65938438-9461fb80-e440-11e9-91eb-413cef1bef0d.png)

**Comment by yuriyz** [comment] 2019-10-01 06:40
It has nothing to do with oxd. CE automatically adding `refresh_token` during dynamic registration if it see `code` response type or `authorization_code` grant_type.

Check these lines:
https://github.com/GluuFederation/oxAuth/blob/d14674992218a9db61f043a6fc1c1bff2b2f20be/Server/src/main/java/org/gluu/oxauth/register/ws/rs/RegisterRestWebServiceImpl.java#L319

**Comment by yuriyz** [comment] 2020-04-22 14:03
It is duplicate of https://github.com/GluuFederation/oxAuth/issues/1252 .

**Closed by yuriyz** 2020-04-22 14:03 UTC
Labels: question
