### ISSUE TITLE
Add brute force protection to default password authentication

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#862] opened 2018-08-01 14:53 UTC
We should cache authentication attempts for a given username, and add a delay of 5 seconds for before every fourth attempt. It would nice if we could expose this feature for use in interception scripts too.

**Comment by yurem** [comment] 2018-08-22 20:05
Implemented and updated [default](https://github.com/GluuFederation/community-edition-setup/commit/2ab105ad9fed327e6b7656a4ec1dff76be4423ea) oxAuth config. It's turn off by default to support backward compatibility with 3.1.x.

Here is new config with values description:
```
	"authenticationProtectionConfiguration": {
		"attemptExpiration": 15, // How long store in cache information about particular login attempt. It's needed to count login attempts withing specified period of time
		"maximumAllowedAttempts": 10, // How many attempts application can allow. It's reserved to use in custom script. For example script can lock user account after specified number of attempts.
		"maximumAllowedAttemptsWithoutDelay": 4, // How many attempts application allow without delay
		"delayTime": 2, // Delay time in seconds after reaching maximumAllowedAttemptsWithoutDelay limit.
		"bruteForceProtectionEnabled": false // Enable or disable service, This functionality can be enabled dynamically. All other values requires restart
	}
```

oxAuth uses new service when there is no person script or when script call basic authentication API.

To get current list of non expired attempts from script we can use next code:
```
from org.xdi.service.cdi.util import CdiUtil
from org.xdi.oxauth.service import AuthenticationProtectionService

...
            authenticationProtectionService = CdiUtil.bean(AuthenticationProtectionService)
            nonExpiredAttempts = authenticationProtectionService.getNonExpiredAttempts(user_name)
...
            isReachAttemptCountLimit = authenticationProtectionService.isReachAttemptCountLimit(user_name)
```

**Comment by yurem** [comment] 2018-08-22 20:06
Let me know if we need to change properties names or enable it by default

**Comment by natt-tester** [comment] 2018-09-11 02:49
@yurem, I've tested it in a fresh VM with Ubuntu 16 (RC3) with the following settings:
<img width="1065" alt="settings1" src="https://user-images.githubusercontent.com/38302725/45334927-56d5ca80-b5c0-11e8-941a-96fcc696b20f.png">
<img width="1087" alt="settings2" src="https://user-images.githubusercontent.com/38302725/45334683-280b2480-b5bf-11e8-915a-487cb965b121.png">
<img width="1116" alt="settings3" src="https://user-images.githubusercontent.com/38302725/45334688-2f323280-b5bf-11e8-8312-6b92f7a8a022.png">
The delay started working, but clicking Login again gave me a proxy error:

Also, **what's the expected behavior?** After reaching the attempts limit without delays, should the user be unable to log in with an incorrect credentials message?

**Comment by yurem** [comment] 2018-09-11 17:39
@natt-tester can you check if there is no proxy error in new CE version?

**Comment by natt-tester** [comment] 2018-09-12 02:54
@yurem, I can't reproduce the proxy error in RC4. However, the question of the expected behavior still stands. Is the delay time in seconds? What's the limit? If I set it to 600, how should it affect the basic login process with the below settings?

<img width="764" alt="set1" src="https://user-images.githubusercontent.com/38302725/45399266-bf897980-b68a-11e8-988f-d7155594b32c.png">

![delay1](https://user-images.githubusercontent.com/38302725/45399196-82bd8280-b68a-11e8-8a25-b744b413cdd5.gif)

**Comment by willow9886** [comment] 2018-09-12 16:50
> Is the delay time in seconds?

Yes, it should be. All configuration time values are seconds as far as I know. 

Ill let @yurem comment on the other questions.

**Comment by natt-tester** [comment] 2018-09-17 07:07
@yurem, could you

**Comment by yurem** [comment] 2018-09-17 09:37
@natt-tester ` If I set it to 600, how should it affect the basic login process with the below settings?`: yes, admin can do this. User will get timeout or proxy error.
I've fixed typo in label.

**Comment by natt-tester** [comment] 2018-09-19 03:55
@yurem I've tested the setup you sent me:
<img width="1125" alt="brute" src="https://user-images.githubusercontent.com/38302725/45728877-57e4a880-bc0d-11e8-8f48-1b2c749f3c13.png">

and my observations are as follows:

- the functionality itself worked, but waiting 1min for oxtrust to load the changes didn't work, had to restart the service to change maximumAllowedAttemptsWithoutDelay (cache clearing and a new incognito window didn't work either)

- when I changed the delayTime to 200, it broke the functionality: before there was a delay after every 4th login request, and in this scenario the delay occurred after every request starting with the 4th one

- I still don't know what maximumAllowedAttempts does: changing the number didn't seem to influence the behavior

Could you please provide an exact description on how it's supposed to work? I can do more exploratory testing, but I don't think this is optimal before the release.

**Comment by yurem** [comment] 2018-09-20 05:44
1. Can you try if reload configuration work well in RC6?
2. 200 seconds is wrong value. You will get proxy timeout or other error not related to oxAuth. See original subject. The right value should be at least less than 20 seconds.
3. I removed `maximumAllowedAttempts` it in order RC6 to avoid questions. `maximumAllowedAttemptsWithoutDelay` is enough for this flow.

**Comment by natt-tester** [comment] 2018-09-21 05:26
@yurem, please tag me in all related comments 

1. **Yes, the reload configuration works well now, tested in c7 with several different settings.**
2. I know what the original idea is, but then why do we have these fields editable with no min/max values info? I think it would make a great UX difference, and it's better to ask now than wait for users' questions
3. Good call ;)

**Comment by yurem** [comment] 2018-09-24 12:01
@natt-tester From my point of view it's admin responsibility about to make decision about right value.

For example: How we can explain him that we not allow to specify in this field value bigger than 100 or 150?

**Comment by yurem** [comment] 2018-09-24 12:06
Currently there is no upper limit of each configuration values in oxAuht/oxTrust: https://github.com/GluuFederation/oxTrust/blob/master/static/src/main/resources/META-INF/resources/schema/oxauth-config.xml.json

From my point of view we need to open separate issue and make decisions after discussion that if we need to apply upper limit to all integer value in configure.

**Comment by natt-tester** [comment] 2018-09-25 09:44
@yurem, it's a good idea to discuss it further -- I think at least an info string for a field would be nice if we don't want to introduce any limits. Apart from that, I've tested the functionality with different settings in RC7 and it seems to be working fine. I'm closing this issue.

**Closed by natt-tester** 2018-09-25 09:44 UTC
Labels: enhancement
