### ISSUE TITLE
oxAuth Does Not Enforce Registered `post_logout_redirect_uri`

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/oxAuth#927] opened 2018-10-22 18:56 UTC
A client with a `post_logout_redirect_uri` registered in oxTrust will not enforce this requirement, and will instead allow any post logout redirect uri to be appended to the end session request.

For example the below would redirect the user to `evil.com`:

```
https://good.gluu.org/oxauth/restv1/end_session?post_logout_redirect_uri=https://evil.com/
```

If this redirect uri is not registered, the user should not be redirected to that end point.

**Comment by yuriyz** [comment] 2018-10-22 20:08
@afroDC I've just tried it against ce-dev3 and it returns 400 (bad request) with error `post_logout_uri_not_associated_with_client`. Would you be so kind to try it against our ce-dev3 and record your http request/responses ?

**Comment by yuriyz** [comment] 2018-10-23 06:53
@afroDC @aliaksander-samuseu this behavior was requested by Yura and added by Eugeniu here https://github.com/GluuFederation/oxAuth/issues/575 .

@yurem I think it makes sense to close this open redirect but then it means that we will return error as it was before (see #575). Do we have functionality that relies on this redirect?

**Comment by yurem** [comment] 2018-11-15 13:59
In issue #575 I requested "Don't show error page on logout when id_token is expired #575". This error page break many integration flows. But I agree to display it when data if wrong. We have to return back to previous issue discussion.

We need to store somehow information about expired tokens. I have one idea. What do you think about adding small AI to grant service cleaner job? I offer to not clean up all expired grants associated with specific user session. We need to keep last created grant (even expired) until new grant will be issued. This small data overhead not make DB very big but will resolve issue which we dicsussed in previous ticket.

**Comment by nynymike** [comment] 2018-11-15 14:16
Sounds like a good idea, as long as the expired grant can't be used to get access to anything by mistake.

**Comment by yurem** [comment] 2018-11-15 14:39
yes, right. This require negative tests and will be useful for cases when cleaner interval is bigger than grant lifetime

**Comment by yuriyz** [comment] 2018-11-15 15:15
What should happen if on next grant creation we call logout with expired `id_token` ? Since `expired` grant will be cleaned up (because according to our AI new grant already created), we will forbid redirect. It will produce inconsistency in behavior and break integration flows as it was prior #575. 

Should we add configuration options which allows or forbids such redirect with default value `false`? Then Admin can explicitly set it to `true` if needed.

**Comment by yurem** [comment] 2018-11-15 15:38
yes, after new grant creation we will remove expired grant. Why RP should call end_session with expired token after new grant creation? It's RP bug.

**Comment by yurem** [comment] 2018-11-15 15:43
This new option will just hide bug which Chris mentioned. Maybe this option will be good with global list of white-listed redirect_uri...?

**Comment by yuriyz** [comment] 2018-11-15 16:00
Right, it seems to be best option for now. If we didn't find out client (because of expired token, grant or client entity itself) then : 

- show error page if `redirect_uri` is not white listed
- redirect if it is white listed.

**Comment by yurem** [comment] 2018-11-15 17:02
@afroDC What do you think? Should this help to resolve this issue?

**Comment by afroDC** [comment] 2018-11-15 17:34
This looks like a valid solution. Have we mitigated any potential complications? @yurem @yuriyz

**Comment by yurem** [comment] 2018-11-20 18:50
I've one new idea. `end_session` endpoint uses `id_token` to validate client. But `id_token` can expire and this led to this issue. Why we are trying to keep expired tokens? There is another way to validate client authority. We can update `end_session` to accept either `id_token`  or `client_id/client_password` (JWT/Basic/PostAuth).

**Comment by afroDC** [comment] 2018-11-20 19:19
@yurem would this violate and deviate from the OpenID spec? https://openid.net/specs/openid-connect-session-1_0-00.html#anchor16

**Comment by nynymike** [comment] 2018-11-22 06:54
I think white listing post logout uri is ok, but isn't it potentially not backwards compatible? If so, we need to make the option configurable.

**Comment by yuriyz** [comment] 2018-11-22 07:46
Right, lets make is configurable (e.g. `allow_post_logout_redirect_without_validation`) with default value false. To summarize:

If we didn't find out client (because of expired token, grant or client entity itself) then :
- if `allow_post_logout_redirect_without_validation`=true -> redirect as it is now;
- if `allow_post_logout_redirect_without_validation`=false -> check white listed redirect_uris. If white listed then allow redirect, if not then show error page.

**Comment by yuriyz** [comment] 2018-11-26 12:36
done in 3.1.5 and master

**Comment by sahiliamsso** [comment] 2018-12-18 03:45
I am able to reproduce even after setting allowPostLogoutRedirectWithoutValidation to false
https://c7.gluu.org/oxauth/restv1/end_session?post_logout_redirect_uri=https%3A%2F%2Fevil.com%2F

**Comment by yuriyz** [comment] 2018-12-18 11:55
It happens because oxauth by default white lists all URIs (via `*` in `clientWhiteList`). Therefore it may looks confusing. I've changed behavior of this feature and updated docs according, now it works as:

1. redirect is forbidden if `allowPostLogoutRedirectWithoutValidation` = false (default value)
2. redirect is allowed if `allowPostLogoutRedirectWithoutValidation` = true and uri is whitelisted.

**Closed by yuriyz** 2018-12-18 11:55 UTC
Labels: High priority, bug
