### ISSUE TITLE
 Logout failed when user logged in two platforms with same session after upgrading from 4.2.3 to 4.3.1

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [GluuFederation/oxAuth#1645] opened 2022-03-02 08:45 UTC
## Describe the issue

 Logout failed when user logged in two platforms with same session after upgrading from 4.2.3 to 4.3.1
 
## Steps To Reproduce
1. Install Gluu-server 4.2.3
1. Go to admin ui.
2. Create two openid-client
3. test sso on both client with same session
4. upgrade gluu-server 4.2.3 to 4.3.1
5. when the upgrade finish test sso for both client with same session 
6. try to logout form one client

## Expected behavior

 As user logged out from one client, it should be logged out form second client 
 
## Actual behavior

loggout failed on second client 

## Desktop (please complete the following information):
 - OS: ubuntu20.04
 - Gluu version 4.3.1

<details>
<summary>Logs</summary>

```
2022-02-24 08:35:24,428 DEBUG [qtp1831477404-21] [org.gluu.oxauth.service.ClientService] (ClientService.java:133) - Found 1 entries for client id = 1001.e0f693df-0d3f-4ed2-b43e-68af190319a2
2022-02-24 08:35:24,428 TRACE [qtp1831477404-21] [org.gluu.oxauth.service.RedirectionUriService] (RedirectionUriService.java:181) - Validating post logout redirect URI: postLogoutRedirectUri = https://test2.gluu.org/identity/finishlogout.htm
2022-02-24 08:35:24,428 DEBUG [qtp1831477404-21] [org.gluu.oxauth.service.RedirectionUriService] (RedirectionUriService.java:132) - Comparing https://test2.gluu.org/idp/profile/Logout == https://test2.gluu.org/identity/finishlogout.htm
2022-02-24 08:35:24,428 DEBUG [qtp1831477404-21] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:72) - Looking for the error with id: post_logout_uri_not_associated_with_client
2022-02-24 08:35:24,428 DEBUG [qtp1831477404-21] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:77) - Found error, id: post_logout_uri_not_associated_with_client
2022-02-24 08:35:24,429 ERROR [qtp1831477404-21] [gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl] (EndSessionRestWebServiceImpl.java:351) - HTTP 400 Bad Request
javax.ws.rs.WebApplicationException: HTTP 400 Bad Request
	at org.gluu.oxauth.model.error.ErrorResponseFactory.createWebApplicationException(ErrorResponseFactory.java:102) ~[classes/:?]
	at org.gluu.oxauth.model.error.ErrorResponseFactory$Proxy$_$$_WeldClientProxy.createWebApplicationException(Unknown Source) ~[classes/:?]
	at org.gluu.oxauth.service.RedirectionUriService.validatePostLogoutRedirectUri(RedirectionUriService.java:193) ~[classes/:?]
	at org.gluu.oxauth.service.RedirectionUriService$Proxy$_$$_WeldClientProxy.validatePostLogoutRedirectUri(Unknown Source) ~[classes/:?]
	at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.validatePostLogoutRedirectUri(EndSessionRestWebServiceImpl.java:334) ~[classes/:?]
	at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl.requestEndSession(EndSessionRestWebServiceImpl.java:127) ~[classes/:?]
	at org.gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl$Proxy$_$$_WeldClientProxy.requestEndSession(Unknown Source) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:249) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:60) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:55) ~[resteasy-core-4.5.7.Final.jar:4.5.7.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[servlet-api-3.1.jar:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1631) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:228) ~[websocket-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.gluu.oxauth.audit.debug.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:67) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:201) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.gluu.server.filters.AbstractCorsFilter.handleNonCORS(AbstractCorsFilter.java:362) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.server.filters.AbstractCorsFilter.doFilter(AbstractCorsFilter.java:139) ~[oxcore-server-4.3.1.Final.jar:?]
	at org.gluu.oxauth.filter.CorsFilter.doFilter(CorsFilter.java:118) ~[classes/:?]
	at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:600) ~[jetty-security-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) ~[jetty-servlet-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.Server.handle(Server.java:516) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400) ~[jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) [jetty-server-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) [jetty-util-9.4.44.v20210927.jar:9.4.44.v20210927]
	at java.lang.Thread.run(Thread.java:829) [?:?]
2022-02-24 08:35:24,433 DEBUG [qtp1831477404-21] [gluu.oxauth.session.ws.rs.EndSessionRestWebServiceImpl] (EndSessionRestWebServiceImpl.java:232) - 
2022-02-24 08:35:24,433 DEBUG [qtp1831477404-21] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:72) - Looking for the error with id: post_logout_uri_not_associated_with_client
2022-02-24 08:35:24,433 DEBUG [qtp1831477404-21] [org.gluu.oxauth.model.error.ErrorResponseFactory] (ErrorResponseFactory.java:77) - Found error, id: post_logout_uri_not_associated_with_client
2022-02-24 08:35:32,989 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:32,989 TRACE [oxAuthScheduler_Worker-1] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.ConfigurationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1894685019
2022-02-24 08:35:32,989 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:32,992 TRACE [ForkJoinPool.commonPool-worker-7] [org.gluu.oxauth.model.config.ConfigurationFactory] (ConfigurationFactory.java:259) - LDAP revision: 3, server revision:3
2022-02-24 08:35:32,996 DEBUG [oxAuthScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:32,997 TRACE [oxAuthScheduler_Worker-5] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.LoggerUpdateEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1629862919
2022-02-24 08:35:32,997 DEBUG [oxAuthScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,011 DEBUG [oxAuthScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:33,011 TRACE [oxAuthScheduler_Worker-4] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.LdapStatusEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 828519173
2022-02-24 08:35:33,011 DEBUG [oxAuthScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,019 INFO  [ForkJoinPool.commonPool-worker-7] [org.gluu.service.logger.LoggerService] (LoggerService.java:205) - Updated log level of '126' loggers to TRACE
2022-02-24 08:35:33,024 DEBUG [oxAuthScheduler_Worker-3] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:33,024 TRACE [oxAuthScheduler_Worker-3] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.CleanerEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1985517234
2022-02-24 08:35:33,025 DEBUG [oxAuthScheduler_Worker-3] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,036 DEBUG [oxAuthScheduler_Worker-2] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:33,037 TRACE [oxAuthScheduler_Worker-2] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.oxauth.service.cdi.event.KeyGenerationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 901146085
2022-02-24 08:35:33,037 DEBUG [oxAuthScheduler_Worker-2] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,041 DEBUG [ForkJoinPool.commonPool-worker-7] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvider.java:282) - Start NATIVE_PERSISTENCE clean up
2022-02-24 08:35:33,044 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:33,044 TRACE [oxAuthScheduler_Worker-1] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.oxauth.service.cdi.event.StatEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1892298587
2022-02-24 08:35:33,044 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,045 DEBUG [ForkJoinPool.commonPool-worker-7] [org.gluu.service.cache.NativePersistenceCacheProvider] (NativePersistenceCacheProvider.java:289) - End NATIVE_PERSISTENCE clean up, items removed: 1
2022-02-24 08:35:33,052 DEBUG [oxAuthScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:33,053 TRACE [oxAuthScheduler_Worker-5] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.oxauth.service.cdi.event.AuthConfigurationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 2062832958
2022-02-24 08:35:33,053 DEBUG [oxAuthScheduler_Worker-5] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:33,053 TRACE [ForkJoinPool.commonPool-worker-3] [org.gluu.oxauth.service.AppInitializer] (AppInitializer.java:307) - Attempting to use persistenceEntryManager: org.gluu.persist.ldap.operation.impl.LdapOperationServiceImpl@6528d339
2022-02-24 08:35:34,071 DEBUG [oxAuthScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:34,071 TRACE [oxAuthScheduler_Worker-4] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.UpdateScriptEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1241052057
2022-02-24 08:35:34,082 DEBUG [oxAuthScheduler_Worker-4] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:47,996 DEBUG [oxAuthScheduler_Worker-3] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:35:47,997 TRACE [oxAuthScheduler_Worker-3] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.LoggerUpdateEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1992328662
2022-02-24 08:35:47,997 DEBUG [oxAuthScheduler_Worker-3] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:35:48,010 INFO  [ForkJoinPool.commonPool-worker-3] [org.gluu.service.logger.LoggerService] (LoggerService.java:205) - Updated log level of '126' loggers to TRACE
2022-02-24 08:36:02,989 DEBUG [oxAuthScheduler_Worker-2] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:36:02,989 TRACE [oxAuthScheduler_Worker-2] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.ConfigurationEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1410148349
2022-02-24 08:36:02,989 DEBUG [oxAuthScheduler_Worker-2] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended
2022-02-24 08:36:02,992 TRACE [ForkJoinPool.commonPool-worker-3] [org.gluu.oxauth.model.config.ConfigurationFactory] (ConfigurationFactory.java:259) - LDAP revision: 3, server revision:3
2022-02-24 08:36:02,997 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:53) - Bound request started
2022-02-24 08:36:02,997 TRACE [oxAuthScheduler_Worker-1] [org.gluu.service.timer.TimerJob] (TimerJob.java:35) - Fire timer event [org.gluu.service.cdi.event.LoggerUpdateEvent] with qualifiers [@org.gluu.service.cdi.event.Scheduled()] from instance 1482834553
2022-02-24 08:36:02,997 DEBUG [oxAuthScheduler_Worker-1] [org.gluu.service.timer.RequestJobListener] (RequestJobListener.java:63) - Bound request ended

```
</details>

**Comment by harrdou** [comment] 2022-03-13 16:35
Looks to be a duplicate of #1651

**Comment by yuriyz** [comment] 2022-03-14 08:05
Yes, it is. Closing it as duplicate. Thanks @harrdou

**Closed by yuriyz** 2022-03-14 08:05 UTC
Labels: bug
