### ISSUE TITLE
Enable id_token public sub claim mapping per client

### ISSUE THREAD

**Issue by nynymike** [GluuFederation/oxAuth#1489] opened 2020-11-02 03:06 UTC
It's possible that a certain client may want to receive a different identifier as the sub value of an id_token. For example, perhaps most clients are ok with the email address as the sub value. But anohter client wants the username. It would be nice if there was a way to set this on a per client basis.

**Comment by yuriyz** [comment] 2020-11-02 09:13
Duplicate of https://github.com/GluuFederation/oxAuth/issues/1336

**Closed by yuriyz** 2020-11-02 09:13 UTC
Labels: enhancement
