### ISSUE TITLE
Username not editable on Gluu login page for Dynamic OIDC 

### ISSUE THREAD

**Issue by sahiliamsso** [GluuFederation/oxAuth#299] opened 2016-08-30 09:51 UTC
When providing account name like this format admin@seed.gluu.org at mod_auth_opeind's page and submitting the request it takes to the Gluu server login form where username field is already populated with admin@seed.gluu.org and is not editable.  This gives error because admin@seed.gluu.org doesn't exist in LDAP. This [case](https://support.gluu.org/integrations/dynamic-registration-of-openidconnect-failing-3120/#at14162) can be referred for more details

**Comment by willow9886** [comment] 2016-08-30 21:25
@yuriyz maybe you can provide some guidance on this?

**Comment by yuriyz** [comment] 2016-08-30 21:29
@willow9886 not sure. @sahiliamsso  where do we have mod_auth_opeind's page ?

Would you please provide screenshot as well as steps to reproduce it on any of our test servers ?

**Comment by willow9886** [comment] 2016-08-30 21:30
@yuriyz I think there's more information here: https://support.gluu.org/integrations/dynamic-registration-of-openidconnect-failing-3120/#at14162

This is a ticket from one of our partners... 

But perhaps @sahiliamsso can also provide additional details.

**Comment by sahiliamsso** [comment] 2016-08-31 12:53
[openid_dynamic.docx](https://github.com/GluuFederation/oxAuth/files/447226/openid_dynamic.docx)
Please find attached steps to reproduce with screenshots. Let me know if you need additional info

**Comment by yuriyz** [comment] 2016-08-31 15:30
reassigning to @qbert2k since login_hint was introduced by him.

**Comment by sahiliamsso** [comment] 2016-11-09 06:08
do we have any updates?

**Closed** 2016-12-30 20:40 UTC
