### ISSUE TITLE
Add support for account switching

### ISSUE THREAD

**Issue by qbert2k** [GluuFederation/oxAuth#809] opened 2018-05-16 20:46 UTC
Add support for prompt = select_account

See ticket: https://support.gluu.org/access-management/5403/authorize-with-select-account/

**Comment by mtgluu** [comment] 2018-05-16 21:07
Javier is this related to account chooser? (http://openid.net/wg/ac/)

**Comment by yuriyz** [comment] 2020-04-22 08:30
It's duplicate of https://github.com/GluuFederation/oxAuth/issues/1290 which is already implemented in 4.2.

**Closed by yuriyz** 2020-04-22 08:30 UTC
Labels: enhancement, new feature
