### ISSUE TITLE
JWT signature fails when using algorithms other than RSA

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/oxAuth#1210] opened 2019-12-05 00:46 UTC
I encountered a problem in JWT signature verification with OxAuthCryptoProvider. It seems it only succeeds when the algorithm is RSA based, not with HS and EC algos

I was able to reproduce in 3.1.x and 4.0. The following is an example based on SCIM RP keys but passport RP can also be used.

## steps to reproduce

Pick a key from scim-rp.jks, eg. `b290d965-5fc9-409b-8c77-bb04982d0944_sig_es256` and export the private key  (download my keystore [here](https://github.com/GluuFederation/oxAuth/files/3924587/scim-rp.jks.txt)):

`# /opt/jre/bin/java -cp '/home/jetty/lib/*' org.gluu.oxauth.util.KeyExporter -keystore scim-rp.jks -keypasswd secret -alias b290d965-5fc9-409b-8c77-bb04982d0944_sig_es256 -exportfile scim-private-key.pem`

Generate a JWT and sign with the private key (use this [javascript](https://github.com/GluuFederation/oxAuth/files/3924589/test.js.txt) file or [python](https://github.com/GluuFederation/oxAuth/files/3924591/test.py.txt) file as guide). I used both to test.

`# node test.js`

Verify the signature of the token. I used jython for agility (paste the token obtained in the RHS of jwt variable below):

```
...
from org.gluu.oxauth.model.jwt import Jwt
from org.gluu.oxauth.model.configuration import AppConfiguration
from org.gluu.oxauth.model.common import WebKeyStorage
from org.gluu.oxauth.model.crypto import CryptoProviderFactory
...

	def check(self):
		jwt = Jwt.parse("eyJhb...
		appConfiguration = AppConfiguration()
		appConfiguration.setWebKeysStorage(WebKeyStorage.KEYSTORE)
		appConfiguration.setKeyStoreFile('/install/community-edition-setup/output/scim-rp.jks')
		appConfiguration.setKeyStoreSecret('secret')

		cryptoProvider = CryptoProviderFactory.getCryptoProvider(appConfiguration)
		return cryptoProvider.verifySignature(jwt.getSigningInput(), jwt.getEncodedSignature(), jwt.getHeader().getKeyId(), None, None, jwt.getHeader().getAlgorithm())
```

The call to `check` returns `False` and oxauth.log shows:

```
2019-12-05 00:09:25,027 ERROR [oxAuthScheduler_Worker-1] [org.gluu.oxauth.model.crypto.OxAuthCryptoProvider] (OxAuthCryptoProvider.java:273) - error decoding signature bytes.
java.security.SignatureException: error decoding signature bytes.
	at org.bouncycastle.jcajce.provider.asymmetric.util.DSABase.engineVerify(Unknown Source) ~[bcprov-jdk15on-1.54.jar:1.54.0]
	at java.security.Signature$Delegate.engineVerify(Signature.java:1222) ~[?:1.8.0_222]
	at java.security.Signature.verify(Signature.java:655) ~[?:1.8.0_222]
	at org.gluu.oxauth.model.crypto.OxAuthCryptoProvider.verifySignature(OxAuthCryptoProvider.java:268) [oxauth-model-4.0.Final.jar:?]
```

If I change, say, to key `4c0ef252-909f-4674-92da-ea8168c9767c_sig_rs256`, export private key, and change algorithm in scripts, the validation passes.

**Comment by yuriyz** [comment] 2019-12-05 20:14
It's bug, for EC algorithm signature is not transcoded and therefore verification fails. Both jwt.io and nimbus confirmed it.

**Comment by yuriyz** [comment] 2019-12-05 20:16
Fixed it with https://github.com/GluuFederation/oxAuth/commit/ada654d93810f7b96c055411b5102099b78c930c . Not closing it yet, we must carefully cover it with tests.

**Comment by yuriyz** [comment] 2019-12-06 07:52
I've fixed oxauth cryptoProvider and oxauth ecdsaSigner. At least now JWT created by third-party lib is verified successfully by jwt.io, nimbus, oxauth cryptoProvider and oxauth ecdsaSigner.

However after full re-build and tests re-run we got 58 test failures. (Which can be seen here: https://ox.gluu.org/jenkins/job/oxAuth_4.1_LDAP/259/)

That makes me think that we have bug in JWT generation for EC algorithms as well. To check it I perform following: 
1) take JWT -> validate by nimbus, oxauth cryptoProvider and oxauth ecdsaSigner
2) generate JWT by nimbus -> validate by nimbus, oxauth cryptoProvider and oxauth ecdsaSigner
3) generate JWT by oxauth -> validate by nimbus, oxauth cryptoProvider and oxauth ecdsaSigner

It gives full picture of compatibility and whether generator and verifier works correctly.

Here is result:
```
JWT (validated by jwt.io): eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImIyOTBkOTY1LTVmYzktNDA5Yi04Yzc3LWJiMDQ5ODJkMDk0NF9zaWdfZXMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImlzcyI6IjEyMDIuZDUwYTRlZWItYWI1ZC00NzRiLWFhYWYtZTRhYTQ3YmM1NGE1IiwianRpIjoiMC4yNTA0MDgyNDU4NTk3Njk0IiwiZXhwIjoxNTc1NTYyODc2Ljg4OCwiaWF0IjoxNTc1NTU5Mjc2ODg4LCJhdWQiOiJodHRwczovL2dvbWVyLXZib3gvb3hhdXRoL3Jlc3R2MS90b2tlbiJ9.8zog9hJwKkytOFqbSuvkgoLJaA9ITqqqAraxxF2m23OwjMKlHYJUlG5UnwxayCZLaF3dEbNxlIHA-OrUPBZLqA
Nimbus verify: true
oxauth cryptoProvider verify: true
oxauth ecdsaSigner verify: true
Nimbus JWT: eyJraWQiOiJiMjkwZDk2NS01ZmM5LTQwOWItOGM3Ny1iYjA0OTgyZDA5NDRfc2lnX2VzMjU2IiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImF1ZCI6Imh0dHBzOlwvXC9nb21lci12Ym94XC9veGF1dGhcL3Jlc3R2MVwvdG9rZW4iLCJpc3MiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImV4cCI6MTU3NTU1OTI3Njg4OCwiaWF0IjoxNTc1NTU5Mjc2ODg4fQ.ji9Me_nQ48T7euNkeoilrfu0TUURGo1suuA9gXJU4dzw-ayXpEvnTdRTvAAJNdKCYksXW7fB2wjRbMLFhdRnrA
Nimbus verify: true
oxauth cryptoProvider verify: true
oxauth ecdsaSigner verify: true
oxauth JWT: eyJraWQiOiJiMjkwZDk2NS01ZmM5LTQwOWItOGM3Ny1iYjA0OTgyZDA5NDRfc2lnX2VzMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImF1ZCI6Imh0dHBzOi8vZ29tZXItdmJveC9veGF1dGgvcmVzdHYxL3Rva2VuIiwiaXNzIjoiMTIwMi5kNTBhNGVlYi1hYjVkLTQ3NGItYWFhZi1lNGFhNDdiYzU0YTUiLCJleHAiOjE1NzU1NTkyNzY4ODgsImlhdCI6MTU3NTU1OTI3Njg4OH0.MEUCIQCnPPCTylyc9s09Uz6Pe9_gO9DP-a7z1bGNqS6hV8BmUQIgW3QH3d1wTsjLY09Hc0ekeEFXBChvM6WIzHf3fA0JXKg
Nimbus verify: false
2019-12-06 09:40:42,119 ERROR [main] [org.gluu.oxauth.model.crypto.OxAuthCryptoProvider] (OxAuthCryptoProvider.java:281) - error decoding signature bytes.
java.security.SignatureException: error decoding signature bytes.
	at org.bouncycastle.jcajce.provider.asymmetric.util.DSABase.engineVerify(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at java.security.Signature$Delegate.engineVerify(Signature.java:1219) ~[?:1.8.0_77]
	at java.security.Signature.verify(Signature.java:652) ~[?:1.8.0_77]
	at org.gluu.oxauth.model.crypto.OxAuthCryptoProvider.verifySignature(OxAuthCryptoProvider.java:276) [classes/:?]
	at org.gluu.oxauth.comp.OxAuthCryptoProviderTest.validate(OxAuthCryptoProviderTest.java:103) [test-classes/:?]
	at org.gluu.oxauth.comp.OxAuthCryptoProviderTest.main(OxAuthCryptoProviderTest.java:47) [test-classes/:?]
oxauth cryptoProvider verify: false
2019-12-06 09:40:42,128 ERROR [main] [org.gluu.oxauth.model.jws.AbstractJwsSigner] (AbstractJwsSigner.java:56) - java.security.SignatureException: error decoding signature bytes.
java.security.SignatureException: java.security.SignatureException: error decoding signature bytes.
	at org.gluu.oxauth.model.jws.ECDSASigner.validateSignature(ECDSASigner.java:151) ~[classes/:?]
	at org.gluu.oxauth.model.jws.AbstractJwsSigner.validate(AbstractJwsSigner.java:51) [classes/:?]
	at org.gluu.oxauth.comp.OxAuthCryptoProviderTest.validate(OxAuthCryptoProviderTest.java:108) [test-classes/:?]
	at org.gluu.oxauth.comp.OxAuthCryptoProviderTest.main(OxAuthCryptoProviderTest.java:47) [test-classes/:?]
Caused by: java.security.SignatureException: error decoding signature bytes.
	at org.bouncycastle.jcajce.provider.asymmetric.util.DSABase.engineVerify(Unknown Source) ~[bcprov-jdk15on-1.64.jar:1.64.0]
	at java.security.Signature$Delegate.engineVerify(Signature.java:1219) ~[?:1.8.0_77]
	at java.security.Signature.verify(Signature.java:652) ~[?:1.8.0_77]
	at org.gluu.oxauth.model.jws.ECDSASigner.validateSignature(ECDSASigner.java:139) ~[classes/:?]
	... 3 more
oxauth ecdsaSigner verify: false

Process finished with exit code 0

```

It means that we spot another bug. Now during signing with EC algorithms (and this is the reason of 58 test failures).

**Comment by yurem** [comment] 2019-12-06 08:14
I added update to convert JCA DER signature into the concatenated R + S format expected by ECDSA JWS.

**Comment by yurem** [comment] 2019-12-06 08:14
Now there are 3 test failures

**Comment by yurem** [comment] 2019-12-06 08:14
@yuriyz @jgomer2001 I think we need to merge this fix into 4.0.1

**Comment by yuriyz** [comment] 2019-12-06 08:54
Right, it should be transcoded during signing for EC.
Test shows that oxauth JWT with EC is compatible with nimbus
```
JWT (validated by jwt.io): eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImIyOTBkOTY1LTVmYzktNDA5Yi04Yzc3LWJiMDQ5ODJkMDk0NF9zaWdfZXMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImlzcyI6IjEyMDIuZDUwYTRlZWItYWI1ZC00NzRiLWFhYWYtZTRhYTQ3YmM1NGE1IiwianRpIjoiMC4yNTA0MDgyNDU4NTk3Njk0IiwiZXhwIjoxNTc1NTYyODc2Ljg4OCwiaWF0IjoxNTc1NTU5Mjc2ODg4LCJhdWQiOiJodHRwczovL2dvbWVyLXZib3gvb3hhdXRoL3Jlc3R2MS90b2tlbiJ9.8zog9hJwKkytOFqbSuvkgoLJaA9ITqqqAraxxF2m23OwjMKlHYJUlG5UnwxayCZLaF3dEbNxlIHA-OrUPBZLqA
Nimbus verify: true
oxauth cryptoProvider verify: true
oxauth ecdsaSigner verify: true
Nimbus JWT: eyJraWQiOiJiMjkwZDk2NS01ZmM5LTQwOWItOGM3Ny1iYjA0OTgyZDA5NDRfc2lnX2VzMjU2IiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImF1ZCI6Imh0dHBzOlwvXC9nb21lci12Ym94XC9veGF1dGhcL3Jlc3R2MVwvdG9rZW4iLCJpc3MiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImV4cCI6MTU3NTU1OTI3Njg4OCwiaWF0IjoxNTc1NTU5Mjc2ODg4fQ.hFR7sx9BRYb48pTfPpsBAqtTZrd0uW6PlMh0M7xbC5jsufJiulWhn4e4m-IFSKg_kqoH-lIbkKIrfbDIJbaupQ
Nimbus verify: true
oxauth cryptoProvider verify: true
oxauth ecdsaSigner verify: true
oxauth JWT: eyJraWQiOiJiMjkwZDk2NS01ZmM5LTQwOWItOGM3Ny1iYjA0OTgyZDA5NDRfc2lnX2VzMjU2IiwidHlwIjoiSldUIiwiYWxnIjoiRVMyNTYifQ.eyJzdWIiOiIxMjAyLmQ1MGE0ZWViLWFiNWQtNDc0Yi1hYWFmLWU0YWE0N2JjNTRhNSIsImF1ZCI6Imh0dHBzOi8vZ29tZXItdmJveC9veGF1dGgvcmVzdHYxL3Rva2VuIiwiaXNzIjoiMTIwMi5kNTBhNGVlYi1hYjVkLTQ3NGItYWFhZi1lNGFhNDdiYzU0YTUiLCJleHAiOjE1NzU1NTkyNzY4ODgsImlhdCI6MTU3NTU1OTI3Njg4OH0.egoarOsZzkDXxzoeOmKar5TILRUlGnwKhZLbBiJxw1NdC8whXIMy81GMWkG_pPkCkiTYwbXpypiT1-528HKkpw
Nimbus verify: true
oxauth cryptoProvider verify: true
oxauth ecdsaSigner verify: true
```

**Comment by yurem** [comment] 2019-12-06 21:16
Fixed

**Closed by yurem** 2019-12-06 21:16 UTC
Labels: bug
