### ISSUE TITLE
oxauth memory use and session management

### ISSUE THREAD

**Issue by shouro** [GluuFederation/oxAuth#69] opened 2015-09-04 02:16 UTC
JVM goes out of memory in some cases. in one case user in database was 263229, and allocating 10GB ram fixed it, and in another case 7GB fixed outage.
oxauth is keeping a lot of session data in memory so this may cause this memory problem.

Currently oxauth keep its session data and it monitors if its expired or not and if expired then deletes the data. But if we use Key-Value (KV) database for session management oxauth can tell (at set) KV database to strore this data for some constant time, after that time database itself will deletes it, and if oxauth don't find data in KV database then its expired, oxauth do not need to manage it. We can put this KV database (say Redis or Cassandra) in container and make a distributed KV database for multi-host cluster.

(other things to think about is, which is very unlikely, third-party lib and in worst case scenario framework itself can be very memory hungry.)

**Comment by yuriyz** [comment] 2015-09-04 07:10
oxauth does not keep sessions in memory, data are kept in ldap only. I guess it's some kind of regression. I will check it.

**Comment by shouro** [comment] 2015-09-04 19:25
I think we should use KV database to manage session data. another outage occur recently, tomcat was using 300% cpu and system was down, I was told that the reason was oxauth tries to calculate session validity in ldap and there was so many session data in ldap and so many was created every second than deleted.

**Comment by nynymike** [comment] 2015-09-04 20:44
This had nothing to do with memory... it was because of missing index in LDAP.

**Comment by shouro** [comment] 2015-09-04 23:09
oops!! then I was miss informed about this.

**Comment by yuriyz** [comment] 2015-09-08 15:36
closing the issue as misunderstanding.

**Closed by yuriyz** 2015-09-08 15:36 UTC

**Comment by shouro** [comment] 2015-09-08 16:51
I misunderstood CPU use but I think we need to do something about memory.

**Comment by yuriyz** [comment] 2015-09-09 07:49
@shouro I've benchmarked oxauth and it doesn't use much memory. For example after 18 hours it used ~300Mb if don't take into account peaks. http://ox.gluu.org/doku.php?id=oxauth:profiling

Maybe there was some recent changes that increased memory consumption, I can investigate it. Did you noticed that oxauth takes a lot of memory? Can you give any statistic or at least something or point to server where oxauth takes a lot of memory, so I can take a look in real-time.

**Comment by yurem** [comment] 2015-09-09 10:05
@shouro which memory options you used to start tomcat? I suspect if you don't limit x64 java it can allocate more memory if needed to reduce GC calls
